var myStates =
    [
        { "State": "Alabama", "Short": "AL", "Capital": "Montgomery", "Population": 200603 },
        { "State": "Alaska", "Short": "AK", "Capital": "Juneau", "Population": 31275 },
        { "State": "Arizona", "Short": "AZ", "Capital": "Phoenix", "Population": 1608139 },
        { "State": "Arkansas", "Short": "AR", "Capital": "Little Rock", "Population": 202591 },
        { "State": "California", "Short": "CA", "Capital": "Sacramento", "Population": 466488 },
        {"State" : "Colorado","Short" : "CO","Capital" : "Denver","Population" : 600158},
        {"State" : "Connecticut","Short" : "CT","Capital" : "Hartford","Population" : 124775},
        {"State" : "Delaware","Short" : "DE","Capital" : "Dover","Population" : 26047},
        {"State" : "Florida","Short" : "FL","Capital" : "Tallahassee","Population" : 181376},
        {"State" : "Georgia","Short" : "GA","Capital" : "Atlanta","Population" : 420003},
        {"State" : "Hawaii","Short" : "HI","Capital" : "Honolulu","Population" : 337256},
        {"State" : "Idaho","Short" : "ID","Capital" : "Boise","Population" : 206100},
        {"State" : "Illinois","Short" : "IL","Capital" : "Springfield","Population" : 116250},
        {"State" : "Indiana","Short" : "IN","Capital" : "Indianapolis","Population" : 820445},
        {"State" : "Iowa","Short" : "IA","Capital" : "Des Moines","Population" : 203443},
        {"State" : "Kansas","Short" : "KS","Capital" : "Topeka","Population" : 127473},
        {"State" : "Kentucky","Short" : "KT","Capital" : "Frankfort","Population" : 25527},
        {"State" : "Louisiana","Short" : "LA","Capital" : "Baton Rouge","Population" : 229493},
        {"State" : "Maine","Short" : "ME","Capital" : "Augusta","Population" : 19136},
        {"State" : "Maryland","Short" : "MD","Capital" : "Annapolis","Population" : 38394},
        {"State" : "Massachusetts","Short" : "MA","Capital" : "Boston","Population" : 6177594},
        {"State" : "Michigan","Short" : "MI","Capital" : "Lansing","Population" : 114297},
        {"State" : "Minnesota","Short" : "MN","Capital" : "Saint Paul","Population" : 285068},
        {"State" : "Mississipi","Short" : "MS","Capital" : "Jackson","Population" : 173514},
        {"State" : "Missouri","Short" : "MO","Capital" : "Jefferson City","Population" : 43079},
        {"State" : "Montanta","Short" : "MT","Capital" : "Helena","Population" : 28190},
        {"State" : "Nebraska","Short" : "NE","Capital" : "Lincoln","Population" : 258379},
        {"State" : "Nevada","Short" : "NV","Capital" : "Carson City","Population" : 55274},
        {"State" : "New Hampshire","Short" : "NH","Capital" : "Concord","Population" : 42695},
        {"State" : "New Jersey","Short" : "NJ","Capital" : "Trenton","Population" : 84913},
        {"State" : "New Mexico","Short" : "NM","Capital" : "Santa Fe","Population" : 67947},
        {"State" : "New York","Short" : "NY","Capital" : "Albany","Population" : 97856},
        {"State" : "North Carolina","Short" : "NC","Capital" : "Raleigh","Population" : 403892},
        {"State" : "North Dakota","Short" : "ND","Capital" : "Bismarck","Population" : 61272},
        {"State" : "Ohio","Short" : "OH","Capital" : "Columbus","Population" : 905748},
        {"State" : "Oklahoma","Short" : "OK","Capital" : "Oklahoma City","Population" : 579999},
        {"State" : "Oregon","Short" : "OR","Capital" : "Salem","Population" : 154637},
        {"State" : "Pennsylvania","Short" : "PA","Capital" : "Harrisburg","Population" : 49528},
        {"State" : "Rhode Island","Short" : "RI","Capital" : "Providence","Population" : 178042},
        {"State" : "South Caroline","Short" : "SC","Capital" : "Columbia","Population" : 129272},
        {"State" : "South Dakota","Short" : "SD","Capital" : "Pierre","Population" : 13646},
        {"State" : "Tennessee","Short" : "TN","Capital" : "Nashville","Population" : 601222},
        {"State" : "Texas","Short" : "TX","Capital" : "Austin","Population" : 790390},
        {"State" : "Utah","Short" : "UT","Capital" : "Salt Lake City","Population" : 186440},
        {"State" : "Vermont","Short" : "VT","Capital" : "Montpelier","Population" : 7855},
        {"State" : "Virgina","Short" : "VA","Capital" : "Richmond","Population" : 204214},
        {"State" : "Washington","Short" : "WA","Capital" : "Olympia","Population" : 46478},
        {"State" : "West Virgina","Short" : "WV","Capital" : "Charleston","Population" : 51400},
        {"State" : "Wisconsin","Short" : "WI","Capital" : "Madison","Population" : 233209},
        { "State" : "Wyoming","Short" : "WY","Capital" : "Cheyenne","Population" : 64019}
]
